#!/usr/bin/python


################################################################################
#
#   Description:
#   ------------
#       Converts the git-diff output into an expandable GitHub comment form, and
#       puts into the system clipboard to allow for easy pasting into the GitHub
#       comment.
#
#   Usage:
#   ------
#   (first place this script in one of the directories in $PATH)
#       $> cd path/to/repo/where/you/want/to/diff
#       $> PAGER= git diff [commits range] | github-diff
#       now go to GitHub and paste into the comment box
#
################################################################################


import os
import sys
import tempfile


def die(msg):
    print(msg)
    sys.exit(1)


tmp_file = tempfile.TemporaryFile()
tmp_file.write('<details>\n')
tmp_file.write('<summary>Diff</summary>\n')

# A blank line is necessary after the summary to make sure that the details
# section gets properly formatted
tmp_file.write('\n')

tmp_file.write('```diff\n')

diff_has_something = False

for line in sys.stdin:
    diff_has_something = True
    tmp_file.write(line)

if not diff_has_something:
    die('Empty diff, nothing to do')

tmp_file.write('```')

# Seek to the beginning
tmp_file.seek(0)

contents = tmp_file.read()
os.system("echo '{}' | xclip -selection clipboard".format(contents))

print("GitHub comment-friendly diff copied to clipboard")
